 
sudo: required

language: python

service:
  - docker

before install:
  - docker build -t mrzeznic/data_generator .
  - docker ps -a
  - docker -it data_generator:latest bash

script:
<<<<<<< HEAD:.travis.yml
  - python take_class.py
=======
  - bundle exec rake test
>>>>>>> d24b9839dabab97ac075ed420525d1dfc7685669:.travis.yml
