from faker import Faker

fake = Faker()

print("Provider:\t ", fake.add_provider("pl_PL"))
print("Date this decade:\t ", fake.date_this_decade())
print("IPv4_public:\t ", fake.ipv4_public())
print("Phone nymber:\t ", fake.phone_number())
print("Secondary address:\t ", fake.secondary_address())
print("Address:\t ", fake.address())
print("Date this month:\t ", fake.date_this_month())
print("IPv6:\t ", fake.ipv6())
print("Postal code:\t ", fake.postalcode())
print("Seed:\t ", fake.seed())
print("AM/PM:\t ", fake.am_pm())
print("This year:\t ", fake.date_this_year())
print("ISBN10:\t ", fake.isbn10())
print("Postal code in state:\t ", fake.postalcode_in_state())
print("Instance:\t ", fake.seed_instance())
print("Android platform token:\t ", fake.android_platform_token())
print("Data time:\t ", fake.date_time())
print("ISBN3:\t ", fake.isbn13())
print("Postal code plus 4:\t ", fake.postalcode_plus4())
print("Sentence:\t ", fake.sentence())
print("Email:\t ", fake.ascii_company_email())
print("Date time add:\t ", fake.date_time_ad())
print("ISO8601:\t ", fake.iso8601())
print("Postcode:\t ",fake.postcode())
print("Sentence:\t ", fake.sentences())
print("ASCII email:\t ", fake.ascii_email())
print("Date time beween:\t ", fake.date_time_between())
print("ITIN:\t ", fake.itin())
print("Postcode in state:\t ", fake.postcode_in_state())
# print("Set formatter:\t ", fake.set_formatter())
print("ASCII free email:\t ", fake.ascii_free_email())
print("Date time between dates:\t ", fake.date_time_between_dates())
print("Fake job:\t ", fake.job())
print("Prefix:\t ", fake.prefix())
print("SHA1:\t ", fake.sha1())
print("ASCII safe email:\t ", fake.ascii_safe_email())
print("Date time this country:\t ", fake.date_time_this_century())
print("Language code:\t ", fake.language_code())
print("Prefix female:\t ", fake.prefix_female())
print("SHA256:\t ", fake.sha256())
print("Bank country:\t", fake.bank_country())
print("Data time this decade:\t ", fake.date_time_this_decade())
print("Last name:\t ", fake.last_name())
print("Prefix male:\t ", fake.prefix_male())
print("Simple profile:\t", fake.simple_profile())
print("BBAN:\t ", fake.bban())
print("Date time this month:\t ", fake.date_time_this_month())
print("Last name female:\t ", fake.last_name_female())
print("Profile:\t ", fake.profile())
'''
print(fake.slug())
print(fake.binary())
print(fake.date_time_this_year())
print(fake.last_name_male())
# print(fake.provider())
print(fake.ssn())
print(fake.boolean())
print(fake.day_of_month())
print(fake.latitude())
# print(fake.providers())
print(fake.state())
print(fake.bothify())
print(fake.day_of_week())
print(fake.latlng())
print(fake.pybool())
print(fake.state_abbr())
print(fake.bs())
print(fake.domain_name())
print(fake.lexify())
print(fake.pydecimal())
print(fake.street_address())
print(fake.building_number())
print(fake.domain_word())
print(fake.license_plate())
print(fake.pydict())
print(fake.street_name())
print(fake.catch_phrase())
print(fake.ean())
print(fake.linux_platform_token())
print(fake.pyfloat())
print(fake.street_suffix())
print(fake.century())
print(fake.ean13())
print(fake.linux_processor())
print(fake.pyint())
print(fake.suffix())
print(fake.chrome())
print(fake.ean8())
print(fake.local_latlng())
print(fake.pyiterable())
print(fake.suffix_female())
print(fake.city())
print(fake.ein())
print(fake.locale())
print(fake.pylist())
print(fake.suffix_male())
print(fake.city_prefix())
print(fake.email())
print(fake.location_on_land())
print(fake.pyset())
print(fake.text())
print(fake.city_suffix())
print(fake.file_extension())
print(fake.longitude())
print(fake.pystr())
print(fake.texts())
print(fake.color_name())
print(fake.file_name())
print(fake.mac_address())
print(fake.pystruct())
print(fake.time())
print(fake.company())
print(fake.file_path())
print(fake.mac_platform_token())
print(fake.pytuple())
print(fake.time_delta())
print(fake.company_email())
print(fake.firefox())
print(fake.mac_processor())
# print(fake.random())
print(fake.time_object())
print(fake.company_suffix())
print(fake.first_name())
print(fake.md5())
print(fake.random_choices())
print(fake.time_series())
print(fake.coordinate())
print(fake.first_name_female())
print(fake.military_apo())
print(fake.random_digit())
print(fake.timezone())
print(fake.country())
print(fake.first_name_male())
print(fake.military_dpo())
print(fake.random_digit_not_null())
print(fake.tld())
print(fake.country_code())
print(fake.format())
print(fake.military_ship())
print(fake.random_digit_not_null_or_empty())
print(fake.unix_device())
print(fake.credit_card_expire())
print(fake.free_email())
print(fake.military_state())
print(fake.random_digit_or_empty())
print(fake.unix_partition())
print(fake.credit_card_full())
print(fake.free_email_domain())
print(fake.mime_type())
print(fake.random_element())
print(fake.unix_time())
print(fake.credit_card_number())
print(fake.future_date())
print(fake.month())
print(fake.random_elements())
print(fake.uri())
print(fake.credit_card_provider())
print(fake.future_datetime())
print(fake.month_name())
print(fake.random_int())
print(fake.uri_extension())
print(fake.credit_card_security_code())
# print(fake.get_formatter())
print(fake.msisdn())
print(fake.random_letter())
print(fake.uri_page())
print(fake.cryptocurrency())
print(fake.get_providers())
print(fake.name())
print(fake.random_letters())
print(fake.uri_path())
print(fake.cryptocurrency_code())
print(fake.hex_color())
print(fake.name_female())
print(fake.random_lowercase_letter())
print(fake.url())
print(fake.cryptocurrency_name())
print(fake.hexify())
print(fake.name_male())
print(fake.random_number())
print(fake.user_agent())
print(fake.currency())
print(fake.hostname())
print(fake.null_boolean())
print(fake.random_sample())
print(fake.user_name())
print(fake.currency_code())
print(fake.iban())
print(fake.numerify())
print(fake.random_uppercase_letter())
print(fake.uuid4())
print(fake.currency_name())
print(fake.image_url())
print(fake.opera())
print(fake.randomize_nb_elements())
print(fake.windows_platform_token())
print(fake.date())
print(fake.internet_explorer())
print(fake.paragraph())
print(fake.rgb_color())
print(fake.word())
print(fake.date_between())
print(fake.invalid_ssn())
print(fake.paragraphs())
print(fake.rgb_css_color())
print(fake.words())
print(fake.date_between_dates())
print(fake.ios_platform_token())
# print(fake.parse())
print(fake.safari())
print(fake.year())
print(fake.date_object())
print(fake.ipv4())
print(fake.password())
print(fake.safe_color_name())
print(fake.zipcode())
print(fake.date_of_birth())
print(fake.ipv4_network_class())
print(fake.past_date())
print(fake.safe_email())
print(fake.zipcode_in_state())
print(fake.date_this_century())
print(fake.ipv4_private())
print(fake.past_datetime())
print(fake.safe_hex_color())
print(fake.zipcode_plus4())
'''